version: 2
updates:
  - package-ecosystem: npm
    directory: /wscc-web
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: pip
    directory: /wscc_fixtures
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
